app:
  ports:
    - "8123:8123"
  volumes:
    - ./app:/data
  links:
    - mongo
    - rabbitmq
  image: node
  dns: 8.8.8.8
  working_dir: /data
  entrypoint: /data/launch-app.sh

mongo:
  image: mongo
  volumes:
    - .:/data
  entrypoint: /data/launch-mongo.sh

rabbitmq:
  container_name: 'rabbit'
  ports:
    - "5672:5672"
    - "15672:15672"
  image: rabbitmq
  volumes:
    - .:/data

